### ISSUE TITLE
fail install

### ISSUE THREAD

**Issue by evolighting** [EvergreenPotato/FairSteam_Firefox#2]
telling package broken

**Comment by EvergreenPotato** [comment]
what is your Firefox version? It should be 45+

**Comment by evolighting** [comment]
@EvergreenPotato 
I'm using Firefox dev - 47.0a2 on Fedora 23;
I have tried installing it by downloading the xpi file on github;
Didn't work neither.

Still I have no idea what wrong except what the brower telling me "从此网站下载的附加组件未能安装，因为它看起已损坏"--which says it is broken.

Thanks for your work on the add-on anyway!

**Comment by EvergreenPotato** [comment]
@evolighting 
I checked Firefox Nightly and for some reason extension doesn't work. I don't know if it's my issue or Nightly build isn't stable enough yet. WebExtensions were just introduced in FF45 and they might have messed up something in the dev build. I'll look into this issue in a month.

The extension is working fine with the current version of Firefox (45). I'll check if it's working fine once FF 46 released.

**Comment by evolighting** [comment]
@EvergreenPotato 
Blame it to the Mozilla!
Introducing WebExtensions are somehow a "right" decision, but changing always brings troubles.

Although firefox is not that "fashionable" anymore, I still find it irreplaceable.It is the best browser, I think.

Again, thanks for all your work and devotion!
