### ISSUE TITLE
Firefox addon is broken! Can't be installed even from AMO.

### ISSUE THREAD

**Issue by Jacosci** [EvergreenPotato/FairSteam_Firefox#3]
![image](https://cloud.githubusercontent.com/assets/10607576/24611101/2ae17748-18ab-11e7-8b0a-a730d4195dfa.png)

**Comment by kevinvanrijn** [comment]
Getting this as well.

Using the .xpi from the [manual installation](https://github.com/EvergreenPotato/FairSteam_Firefox#manual) results in the same thing so it's not an issue on Mozilla's side.

**Comment by EvergreenPotato** [comment]
The new fixed version of extension is available here: https://addons.mozilla.org/en-US/firefox/addon/fairsteam/
Thanks for the patience!

**Comment by kevinvanrijn** [comment]
Confirming it works now. Thanks!
